### ISSUE TITLE
有没有具体的使用Demo

### ISSUE THREAD

**Issue by zacksleo** [taliove/weapp-phaser3-adapter#1]
先引入 Phaser， 再引入了 weapp-phaser3-adapter, 报了以下错误
` Cannot read property 'hasOwnProperty' of undefined 
 TypeError: Cannot read property 'hasOwnProperty' of undefined`

**Comment by taliove** [comment]
不好意思。当前解决方案只在微信开发者工具上成功调用。但是真机环境还没有测试通过。

**Comment by vvenv** [comment]
显然是要先引 adapter 再引 phaser
